# Generated by Django 5.0.1 on 2024-02-21 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Editorial',
            new_name='Publisher',
        ),
    ]
