# Generated by Django 5.0.1 on 2024-02-20 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='author_review',
            new_name='profile',
        ),
    ]
