# Generated by Django 5.0.1 on 2024-02-20 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='profile',
            new_name='user_creator',
        ),
    ]
