# Generated by Django 5.0.1 on 2024-02-08 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sinopsis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('isbn', models.CharField(max_length=13)),
                ('author', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('synopsis', models.TextField()),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.editorial')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.gender')),
            ],
        ),
    ]
