# Generated by Django 5.0.1 on 2024-02-19 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genders', '0001_initial'),
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('isbn', models.CharField(max_length=13)),
                ('author', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('synopsis', models.TextField()),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishers.editorial')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genders.gender')),
            ],
        ),
    ]
