# Generated by Django 5.0.1 on 2024-02-08 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='editorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishers.editorial'),
        ),
        migrations.RenameField(
            model_name='gender',
            old_name='sinopsis',
            new_name='synopsis',
        ),
        migrations.DeleteModel(
            name='Editorial',
        ),
    ]
